version: "3.9"
services:
  db:
    container_name: mysql_container
    image: mysql:8.2
    environment:
      MYSQL_DATABASE: 1023c01_GRUPO6
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: 1023c01_GRUPO6
      MYSQL_PASSWORD: Vo7tahh4
    networks:
      - integrador
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    restart: always
networks:
  integrador:
    driver: bridge
volumes:
  db: