services:
  db:
    image: mysql:8.2
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: 1023c01_GRUPO6
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: 1023c01_GRUPO6
      MYSQL_PASSWORD: Vo7tahh4
    networks:
      - integrador
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
networks:
  integrador:
    driver: bridge
volumes:
  db: